version: "2.2"
services:
  jobmanager:
    image: pyflink:1.15.2
    volumes:
    - .:/opt/flink/usrlib
    ports:
      - "8085:8081"
    command: standalone-job -py state_access.py
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
  taskmanager:
    image: pyflink:1.15.2
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
